name = "PreDestiny Matcha+"
author = "d3st1ny"
version = "1.1.2-fabric-26.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c165bd04806f9cdba91607601f763238c1e4893c5ffdffa24e71940df2b649a9"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.1"]
datapack-folder = "datapacks"
