name = "PreDestiny Matcha+"
author = "d3st1ny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f7e5da76ae047a3824bf500098d27e1bb3d415a3429ee5288adc4becc0eb161"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.1", "1.21.1"]
datapack-folder = "datapacks"
