name = "PreDestiny Matcha+"
author = "d3st1ny"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8fa15a81e40ffa253821007705a0db9385c2ccde3467e08544007d51014f3e8b"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = ["26.1", "1.21.1"]
datapack-folder = "datapacks"
